### PR TITLE
Feature/packages component

### PR DESCRIPTION
**Pull request by uma-victor1**
Finished the package Component.

### CODE REVIEW

**Comment by TNortnern** [comment]
@uma-victor1 components should be capitalized, only pages should be lowercased

**Comment by TNortnern** [comment]
I noticed the tab go away on mobile, can we avoid this btw? I know it's done in the designs but it makes no sense for them to go away

**Comment by uma-victor1** [comment]
> @uma-victor1 components should be capitalized, only pages should be lowercased

Didn't know that.
I'll change it.

**Comment by uma-victor1** [comment]
Thanks for the feedback.

**Pull request closed without merging**
