### PR TITLE
Feature/hero

### PR DESCRIPTION
**Pull request by 3than0ls**
I think the images on the right should be all put into one image and using only one image, rather than styling a bunch of different images on top of each other. It would be a lot easier and require a lot less HTML.

While styling for mobile, I noticed that the NavBar has a few issues, like it's width going out of screen width (which I think may be causing the white bar on the right), and that the layer that is shown when the menu opens doesn't stretch across the entire screen, and it also blocks pointer events (even when inactive).

image

### CODE REVIEW

**Comment by uma-victor1** [comment]
The white bar on the right is as a result of.
`w-screen` utility class in tailwind.
It's located in the `navbarMobile` component.

**Comment by uma-victor1** [comment]
Nice work Ethan!.☺

**Comment by TNortnern** [comment]
@3than0ls everything looks good but I would suggest scaling down the text on any breakpoint below 2xl(1536px>). It seems too big. In all honesty it's a little too big for all the components you've done on breakpoints smaller then 2xl.

**Comment by TNortnern** [comment]
so maybe like 2xl:text-8xl and anything below go down to about text-5xl or lower depending on it's purpose. Try to view the component on a screen at 1440px or 1280px which are 2 of the most popular screen widths

**Comment by 3than0ls** [comment]
Sorry about the text size. What happened was I zoomed in on the Figma file until it fit my screen, and then picked all sizes as close as possible. However, I just realized that my monitor width is a a decent amount larger than the target size...oops. I'll try to fix other components and resize those, sorry about that.

**Pull request merged**
